id: P007042
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS16854
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་ཚད་མ་གྲུབ་པའི་ལེའུའི་མཐའ་དཔྱོད།
  author: ''
  volumes:
    1d6c6732afff48f3a8706e96a6ffeabf:
      image_group_id: I8LS16873
      title: ''
      volume_number: 1
      total_pages: 1011
    41fcbb1a3673476c8c89dc123b1e80f5:
      image_group_id: I8LS16874
      title: ''
      volume_number: 2
      total_pages: 716
ebook_metadata:
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་ཚད་མ་གྲུབ་པའི་ལེའུའི་མཐའ་དཔྱོད།
  author: ''
  sku: P007042
  cover: cover.jpg
  layers:
  - pagination
